language: python
sudo: false
cache:
  apt: true
  directories:
    - $HOME/.cache/pip

python:
  - "2.7"

virtualenv:
  system_site_packages: true

services:
  - postgresql

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - python-simplejson
      - python-serial
      - python-yaml
      - python-pychart
      - pdftk
      - imagemagick
      - wkhtmltopdf
      - ttf-dejavu

install:
  - compare -version
  - python bootstrap.py
  - bin/buildout -c buildout.cfg
  - createdb zitcom
  - bin/upgrade_odoo -d zitcom --init-load-demo-data

script:
  - bin/nosetests -d zitcom -- -v zitcom-addons/